#  instance:
#    hostname: fnp-svc-discovery-server-8c7614af535c.herokuapp.com
spring:
  application:
    name: SVC-DISCOVERY
  security:
    user:
      name: ${EUREKA_USERNAME}
      password: ${EUREKA_PASSWORD}
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    registerWithEureka: false
    fetchRegistry: false
    healthcheck: enabled
#    serviceUrl:
#      defaultZone: https://fnp-svc-discovery-server-8c7614af535c.herokuapp.com/eureka/
    serviceUrl:
      defaultZone: ${EUREKA_PROTOCOL}://${EUREKA_URL}/eureka/
