spring:
  application:
    name: SVC-DISCOVERY
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck: enabled
    serviceUrl:
      defaultZone: https://fnp-svc-discovery-server-8c7614af535c.herokuapp.com/eureka/
  instance:
    hostname: fnp-svc-discovery-server-8c7614af535c.herokuapp.com


