#spring:
#  application:
#    name: SVC-DISCOVERY
#server:
#  port: 8761
#eureka:
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    healthcheck: enabled
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  instance:
#    hostname: fnp-svc-discovery-server-8c7614af535c.herokuapp.com
spring:
  application:
    name: SVC-DISCOVERY
  security:
    user:
      name: username
      password: password
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-register: false
    register-with-eureka: false
    registerWithEureka: false
    fetchRegistry: false
    healthcheck: enabled
    serviceUrl:
      defaultZone: https://username:password@fnp-svc-discovery-server-8c7614af535c.herokuapp.com/eureka/

